### ISSUE TITLE
Uncaught TypeError when running compile command.

### ISSUE THREAD

**Issue by kherge** [humbug/box#181]
| Question    | Answer
| ------------| ---------------
| Box version | master
| PHP version | 7.1.2
| Platform with version | macOS

The compile command fails to run because [this closure](https://github.com/humbug/box/blob/c69880d93d50235c9f353a0727789d562a2dc8b2/src/Console/Command/Compile.php#L224) is expected to return a string, but an integer is returned instead.

<details>
 <summary>Uncaught TypeError</summary>
 
 ```
[Mion: kherrera] 07:25:55 box $ bin/box compile -c box.json.dist
PHP Fatal error:  Uncaught TypeError: Return value of KevinGH\Box\Console\Command\Compile::KevinGH\Box\Console\Command\{closure}() must be of the type string, integer returned in /Users/kherrera/Downloads/box/src/Console/Command/Compile.php:224
Stack trace:
#0 /Users/kherrera/Downloads/box/src/Console/Command/Compile.php(230): KevinGH\Box\Console\Command\Compile::KevinGH\Box\Console\Command\{closure}(134217728)
#1 /Users/kherrera/Downloads/box/src/Console/Command/Compile.php(155): KevinGH\Box\Console\Command\Compile::checkPhpSettings(Object(Symfony\Component\Console\Style\SymfonyStyle), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/kherrera/Downloads/box/vendor/symfony/console/Command/Command.php(252): KevinGH\Box\Console\Command\Compile->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/kherrera/Downloads/box/vendor/symfony/console/Application.php(865): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\ in /Users/kherrera/Downloads/box/src/Console/Command/Compile.php on line 224

Fatal error: Uncaught TypeError: Return value of KevinGH\Box\Console\Command\Compile::KevinGH\Box\Console\Command\{closure}() must be of the type string, integer returned in /Users/kherrera/Downloads/box/src/Console/Command/Compile.php on line 224

TypeError: Return value of KevinGH\Box\Console\Command\Compile::KevinGH\Box\Console\Command\{closure}() must be of the type string, integer returned in /Users/kherrera/Downloads/box/src/Console/Command/Compile.php on line 224

Call Stack:
    0.0010     361288   1. {main}() /Users/kherrera/Downloads/box/bin/box:0
    0.0516    1621016   2. KevinGH\Box\Console\Application->run() /Users/kherrera/Downloads/box/bin/box:43
    0.0979    1920152   3. KevinGH\Box\Console\Application->doRun() /Users/kherrera/Downloads/box/vendor/symfony/console/Application.php:143
    0.1206    2676488   4. KevinGH\Box\Console\Application->doRunCommand() /Users/kherrera/Downloads/box/vendor/symfony/console/Application.php:241
    0.1207    2676488   5. KevinGH\Box\Console\Command\Compile->run() /Users/kherrera/Downloads/box/vendor/symfony/console/Application.php:865
    0.1214    2682400   6. KevinGH\Box\Console\Command\Compile->execute() /Users/kherrera/Downloads/box/vendor/symfony/console/Command/Command.php:252
    0.1244    2776248   7. KevinGH\Box\Console\Command\Compile::checkPhpSettings() /Users/kherrera/Downloads/box/src/Console/Command/Compile.php:155
    0.1244    2776600   8. KevinGH\Box\Console\Command\Compile::KevinGH\Box\Console\Command\{closure}() /Users/kherrera/Downloads/box/src/Console/Command/Compile.php:230
 ```
</details>

**Comment by theofidry** [comment]
Closed by #182 and #183
