### ISSUE TITLE
Latest box versions fail with a fatal error on PHP 7.3

### ISSUE THREAD

**Issue by jakzal** [humbug/box#380]
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | phar 3.5.0, 3.5.1, 3.6.0
| PHP version | PHP 7.3
| Platform with version | MacOS, Ubuntu
| Github Repo | https://github.com/jakzal/toolbox/pull/73

Building my project on PHP 7.3 fails with a fatal error: `Call to a member function defer() on null in phar:///Users/kuba/Projects/toolbox/tools/box/vendor/amphp/amp/lib/Loop.php:45`. 

Related build failure on Travis: https://travis-ci.com/jakzal/toolbox/jobs/187201645#L377

Note I'm calling `composer config platform.php 7.1.3` before building the package so the created phar would work with PHP 7.1.

<details>
 <summary>box.json.dist</summary>
 
 ```json
{
    "base-path": "build/phar",
    "output": "../toolbox.phar",
    "compression": "GZ",
    "directories": ["."],
    "dump-autoload": true,
    "exclude-composer-files": true,
    "check-requirements": false,
    "main": "bin/toolbox.php",
    "compactors": [
        "KevinGH\\Box\\Compactor\\PhpScoper"
    ],
    "banner": [
        "This file is part of the zalas/toolbox project."
    ]
}⏎
 ```
</details>

<details>
 <summary>Output</summary>
 
 ```bash
 $ composer config platform.php 7.1.3 && composer update --no-dev -o -a
 $ box compile
 >     ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 3.5.0@cfc7c11 2019-03-05 00:51:30 UTC


 // Loading the configuration file "/Users/kuba/Projects/toolbox/box.json.dist".

🔨  Building the PHAR "/Users/kuba/Projects/toolbox/build/toolbox.phar"

? Registering compactors
  + KevinGH\Box\Compactor\PhpScoper
? Adding main file: /Users/kuba/Projects/toolbox/build/phar/bin/toolbox.php
? Skip requirements checker
? Adding binary files
    > No file found
? Auto-discover files? No
? Exclude dev files? Yes
? Adding files
PHP Fatal error:  Uncaught Error: Call to a member function defer() on null in phar:///Users/kuba/Projects/toolbox/tools/box/vendor/amphp/amp/lib/Loop.php:45
Stack trace:
#0 phar:///Users/kuba/Projects/toolbox/tools/box/vendor/amphp/amp/lib/functions.php(85): _HumbugBox9257ad6c1a66\Amp\Loop::run(Object(Closure))
#1 phar:///Users/kuba/Projects/toolbox/tools/box/src/Box.php(231): _HumbugBox9257ad6c1a66\Amp\Promise\wait(Object(_HumbugBox9257ad6c1a66\Amp\Coroutine))
#2 phar:///Users/kuba/Projects/toolbox/tools/box/src/Box.php(176): _HumbugBox9257ad6c1a66\KevinGH\Box\Box->processContents(Array)
#3 phar:///Users/kuba/Projects/toolbox/tools/box/src/Console/Command/Compile.php(234): _HumbugBox9257ad6c1a66\KevinGH\Box\Box->addFiles(Array, false)
#4 phar:///Users/kuba/Projects/toolbox/tools/box/src/Console/Command/Compile.php(148): _HumbugBox9257ad6c1a66\KevinGH\Box\Console\Command\Compile->addFiles(Object(_HumbugBox
9257ad6c1a66\KevinGH\Box\Configuration), Object(_HumbugBox9257ad6c1a66\KevinGH\Box\Box), Object(_HumbugBox9257ad6c1a66\Kev in phar:///Users/kuba/Projects/toolbox/tools/box/v
endor/amphp/amp/lib/functions.php on line 87
 ```
</details>

**Comment by ondrejmirtes** [comment]
I have the same experience.

**Comment by theofidry** [comment]
I tried to look at it briefly but it's a bit hard to spot. My guess is that it's coming from the amphp upgrade I did. I don't think their code is directly wrong, but there is likely something not being scoped properly.

Meanwhile I would recommend to do with `--no-parallel`. I know it's much slower but I don't think I'll be able to take a deeper look into the issue before next week
